[Definition]
failregex = ^.*pam_unix\(cockpit:auth\): authentication failure;.*rhost=<HOST>.*$
            ^.*authentication failure.*cockpit.*(?:rhost=|from )<HOST>.*$
            ^.*FAILED LOGIN.*(?:from|remote-address=|rhost=)\s*<HOST>.*$
ignoreregex =
