// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: burnbridge.proto

package burnbridgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BurnBridge_CreateJob_FullMethodName    = "/burnbridge.v1.BurnBridge/CreateJob"
	BurnBridge_UploadObject_FullMethodName = "/burnbridge.v1.BurnBridge/UploadObject"
	BurnBridge_CommitJob_FullMethodName    = "/burnbridge.v1.BurnBridge/CommitJob"
	BurnBridge_GetJobStatus_FullMethodName = "/burnbridge.v1.BurnBridge/GetJobStatus"
	BurnBridge_CancelJob_FullMethodName    = "/burnbridge.v1.BurnBridge/CancelJob"
)

// BurnBridgeClient is the client API for BurnBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BurnBridgeClient interface {
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	UploadObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadObjectChunk, UploadObjectResponse], error)
	CommitJob(ctx context.Context, in *CommitJobRequest, opts ...grpc.CallOption) (*CommitJobResponse, error)
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
}

type burnBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewBurnBridgeClient(cc grpc.ClientConnInterface) BurnBridgeClient {
	return &burnBridgeClient{cc}
}

func (c *burnBridgeClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, BurnBridge_CreateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) UploadObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadObjectChunk, UploadObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BurnBridge_ServiceDesc.Streams[0], BurnBridge_UploadObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadObjectChunk, UploadObjectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BurnBridge_UploadObjectClient = grpc.ClientStreamingClient[UploadObjectChunk, UploadObjectResponse]

func (c *burnBridgeClient) CommitJob(ctx context.Context, in *CommitJobRequest, opts ...grpc.CallOption) (*CommitJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitJobResponse)
	err := c.cc.Invoke(ctx, BurnBridge_CommitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, BurnBridge_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, BurnBridge_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BurnBridgeServer is the server API for BurnBridge service.
// All implementations must embed UnimplementedBurnBridgeServer
// for forward compatibility.
type BurnBridgeServer interface {
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	UploadObject(grpc.ClientStreamingServer[UploadObjectChunk, UploadObjectResponse]) error
	CommitJob(context.Context, *CommitJobRequest) (*CommitJobResponse, error)
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	mustEmbedUnimplementedBurnBridgeServer()
}

// UnimplementedBurnBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBurnBridgeServer struct{}

func (UnimplementedBurnBridgeServer) CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedBurnBridgeServer) UploadObject(grpc.ClientStreamingServer[UploadObjectChunk, UploadObjectResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadObject not implemented")
}
func (UnimplementedBurnBridgeServer) CommitJob(context.Context, *CommitJobRequest) (*CommitJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitJob not implemented")
}
func (UnimplementedBurnBridgeServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedBurnBridgeServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedBurnBridgeServer) mustEmbedUnimplementedBurnBridgeServer() {}
func (UnimplementedBurnBridgeServer) testEmbeddedByValue()                    {}

// UnsafeBurnBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BurnBridgeServer will
// result in compilation errors.
type UnsafeBurnBridgeServer interface {
	mustEmbedUnimplementedBurnBridgeServer()
}

func RegisterBurnBridgeServer(s grpc.ServiceRegistrar, srv BurnBridgeServer) {
	// If the following call panics, it indicates UnimplementedBurnBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BurnBridge_ServiceDesc, srv)
}

func _BurnBridge_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_CreateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_UploadObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BurnBridgeServer).UploadObject(&grpc.GenericServerStream[UploadObjectChunk, UploadObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BurnBridge_UploadObjectServer = grpc.ClientStreamingServer[UploadObjectChunk, UploadObjectResponse]

func _BurnBridge_CommitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).CommitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_CommitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).CommitJob(ctx, req.(*CommitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BurnBridge_ServiceDesc is the grpc.ServiceDesc for BurnBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BurnBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "burnbridge.v1.BurnBridge",
	HandlerType: (*BurnBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _BurnBridge_CreateJob_Handler,
		},
		{
			MethodName: "CommitJob",
			Handler:    _BurnBridge_CommitJob_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _BurnBridge_GetJobStatus_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _BurnBridge_CancelJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadObject",
			Handler:       _BurnBridge_UploadObject_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "burnbridge.proto",
}
