// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.9
// source: burnbridge.proto

package burnbridgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BurnBridge_GetVersion_FullMethodName                 = "/burnbridge.v1.BurnBridge/GetVersion"
	BurnBridge_CreateJob_FullMethodName                  = "/burnbridge.v1.BurnBridge/CreateJob"
	BurnBridge_UploadObject_FullMethodName               = "/burnbridge.v1.BurnBridge/UploadObject"
	BurnBridge_CommitJob_FullMethodName                  = "/burnbridge.v1.BurnBridge/CommitJob"
	BurnBridge_CommitJobBatch_FullMethodName             = "/burnbridge.v1.BurnBridge/CommitJobBatch"
	BurnBridge_GetJobStatus_FullMethodName               = "/burnbridge.v1.BurnBridge/GetJobStatus"
	BurnBridge_CancelJob_FullMethodName                  = "/burnbridge.v1.BurnBridge/CancelJob"
	BurnBridge_ReadObject_FullMethodName                 = "/burnbridge.v1.BurnBridge/ReadObject"
	BurnBridge_RegisterS3ObjectPullSource_FullMethodName = "/burnbridge.v1.BurnBridge/RegisterS3ObjectPullSource"
	BurnBridge_TestUnitReady_FullMethodName              = "/burnbridge.v1.BurnBridge/TestUnitReady"
	BurnBridge_WatchUnitStatus_FullMethodName            = "/burnbridge.v1.BurnBridge/WatchUnitStatus"
	BurnBridge_GetDiscInfo_FullMethodName                = "/burnbridge.v1.BurnBridge/GetDiscInfo"
	BurnBridge_HandleMediaChange_FullMethodName          = "/burnbridge.v1.BurnBridge/HandleMediaChange"
	BurnBridge_HandleTray_FullMethodName                 = "/burnbridge.v1.BurnBridge/HandleTray"
	BurnBridge_GetImportedBucketState_FullMethodName     = "/burnbridge.v1.BurnBridge/GetImportedBucketState"
	BurnBridge_DeleteObjects_FullMethodName              = "/burnbridge.v1.BurnBridge/DeleteObjects"
	BurnBridge_ListMetadataDbVersions_FullMethodName     = "/burnbridge.v1.BurnBridge/ListMetadataDbVersions"
	BurnBridge_RestoreMetadataDbVersion_FullMethodName   = "/burnbridge.v1.BurnBridge/RestoreMetadataDbVersion"
	BurnBridge_GetAnchorStatus_FullMethodName            = "/burnbridge.v1.BurnBridge/GetAnchorStatus"
	BurnBridge_ConfigureRuntimeOptions_FullMethodName    = "/burnbridge.v1.BurnBridge/ConfigureRuntimeOptions"
	BurnBridge_FinalizeLayout_FullMethodName             = "/burnbridge.v1.BurnBridge/FinalizeLayout"
	BurnBridge_UpdateLicense_FullMethodName              = "/burnbridge.v1.BurnBridge/UpdateLicense"
	BurnBridge_UploadUpgradePackage_FullMethodName       = "/burnbridge.v1.BurnBridge/UploadUpgradePackage"
	BurnBridge_ApplyUpgrade_FullMethodName               = "/burnbridge.v1.BurnBridge/ApplyUpgrade"
)

// BurnBridgeClient is the client API for BurnBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BurnBridge recorder API.
//
// Compatibility goal:
// - Keep wire fields compatible with versitygw/backend/burnbridge/proto/burnbridge.proto
// - Allow direct interop between Go gateway and .NET Core BurnServer
type BurnBridgeClient interface {
	// Query recorder service version and runtime metadata.
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// Create a logical write job for one S3 object.
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	// Bidirectional upload stream.
	// Server should ack per logical segment and optionally emit final summary ack.
	UploadObject(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadObjectChunk, UploadObjectAck], error)
	// Finalize a job and persist layout/session metadata.
	CommitJob(ctx context.Context, in *CommitJobRequest, opts ...grpc.CallOption) (*CommitJobResponse, error)
	// Finalize multiple uploaded jobs in one recorder drain/flush cycle.
	CommitJobBatch(ctx context.Context, in *CommitJobBatchRequest, opts ...grpc.CallOption) (*CommitJobBatchResponse, error)
	// Query current job status.
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	// Request cooperative cancel.
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
	// Read object bytes by (bucket, object_key) from offset.
	// length == 0 means stream to object end.
	ReadObject(ctx context.Context, in *ReadObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadObjectChunk], error)
	// Register pull source so recorder can fetch bytes directly from S3-compatible endpoint.
	RegisterS3ObjectPullSource(ctx context.Context, in *RegisterS3ObjectPullSourceRequest, opts ...grpc.CallOption) (*RegisterS3ObjectPullSourceResponse, error)
	// Probe whether current unit/session is ready for I/O.
	TestUnitReady(ctx context.Context, in *TestUnitReadyRequest, opts ...grpc.CallOption) (*TestUnitReadyResponse, error)
	// Subscribe to recorder unit/media readiness updates.
	WatchUnitStatus(ctx context.Context, in *WatchUnitStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UnitStatusEvent], error)
	// Query drive + disc information.
	GetDiscInfo(ctx context.Context, in *GetDiscInfoRequest, opts ...grpc.CallOption) (*GetDiscInfoResponse, error)
	// Explicitly notify the recorder about a media insert/remove event.
	HandleMediaChange(ctx context.Context, in *HandleMediaChangeRequest, opts ...grpc.CallOption) (*HandleMediaChangeResponse, error)
	// Explicitly open or close the recorder tray.
	HandleTray(ctx context.Context, in *HandleTrayRequest, opts ...grpc.CallOption) (*HandleTrayResponse, error)
	// Return the currently imported on-disc metadata snapshot maintained by the recorder.
	GetImportedBucketState(ctx context.Context, in *GetImportedBucketStateRequest, opts ...grpc.CallOption) (*GetImportedBucketStateResponse, error)
	// Mark one or more objects as logically deleted in recorder metadata.
	DeleteObjects(ctx context.Context, in *DeleteObjectsRequest, opts ...grpc.CallOption) (*DeleteObjectsResponse, error)
	// List metadata database artifact versions known by the recorder.
	ListMetadataDbVersions(ctx context.Context, in *ListMetadataDbVersionsRequest, opts ...grpc.CallOption) (*ListMetadataDbVersionsResponse, error)
	// Restore a metadata database artifact generation as the recorder's current working view.
	RestoreMetadataDbVersion(ctx context.Context, in *RestoreMetadataDbVersionRequest, opts ...grpc.CallOption) (*RestoreMetadataDbVersionResponse, error)
	// Report BRS anchor state for the active disc/bucket.
	GetAnchorStatus(ctx context.Context, in *GetAnchorStatusRequest, opts ...grpc.CallOption) (*GetAnchorStatusResponse, error)
	// Configure recorder runtime-only options without editing config files or restarting.
	ConfigureRuntimeOptions(ctx context.Context, in *ConfigureRuntimeOptionsRequest, opts ...grpc.CallOption) (*ConfigureRuntimeOptionsResponse, error)
	// Finalize accumulated UDF layout on disc using persisted layout metadata (closes stream write session).
	FinalizeLayout(ctx context.Context, in *FinalizeLayoutRequest, opts ...grpc.CallOption) (*FinalizeLayoutResponse, error)
	// Replace recorder license.xml content and optionally reload the shared burner host.
	UpdateLicense(ctx context.Context, in *UpdateLicenseRequest, opts ...grpc.CallOption) (*UpdateLicenseResponse, error)
	// Upload an upgrade package into the recorder staging directory.
	UploadUpgradePackage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadUpgradePackageChunk, UploadUpgradePackageResponse], error)
	// Execute the configured recorder upgrade apply command for a staged package.
	ApplyUpgrade(ctx context.Context, in *ApplyUpgradeRequest, opts ...grpc.CallOption) (*ApplyUpgradeResponse, error)
}

type burnBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewBurnBridgeClient(cc grpc.ClientConnInterface) BurnBridgeClient {
	return &burnBridgeClient{cc}
}

func (c *burnBridgeClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, BurnBridge_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, BurnBridge_CreateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) UploadObject(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadObjectChunk, UploadObjectAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BurnBridge_ServiceDesc.Streams[0], BurnBridge_UploadObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadObjectChunk, UploadObjectAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BurnBridge_UploadObjectClient = grpc.BidiStreamingClient[UploadObjectChunk, UploadObjectAck]

func (c *burnBridgeClient) CommitJob(ctx context.Context, in *CommitJobRequest, opts ...grpc.CallOption) (*CommitJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitJobResponse)
	err := c.cc.Invoke(ctx, BurnBridge_CommitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) CommitJobBatch(ctx context.Context, in *CommitJobBatchRequest, opts ...grpc.CallOption) (*CommitJobBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitJobBatchResponse)
	err := c.cc.Invoke(ctx, BurnBridge_CommitJobBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, BurnBridge_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, BurnBridge_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) ReadObject(ctx context.Context, in *ReadObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadObjectChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BurnBridge_ServiceDesc.Streams[1], BurnBridge_ReadObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadObjectRequest, ReadObjectChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BurnBridge_ReadObjectClient = grpc.ServerStreamingClient[ReadObjectChunk]

func (c *burnBridgeClient) RegisterS3ObjectPullSource(ctx context.Context, in *RegisterS3ObjectPullSourceRequest, opts ...grpc.CallOption) (*RegisterS3ObjectPullSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterS3ObjectPullSourceResponse)
	err := c.cc.Invoke(ctx, BurnBridge_RegisterS3ObjectPullSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) TestUnitReady(ctx context.Context, in *TestUnitReadyRequest, opts ...grpc.CallOption) (*TestUnitReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestUnitReadyResponse)
	err := c.cc.Invoke(ctx, BurnBridge_TestUnitReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) WatchUnitStatus(ctx context.Context, in *WatchUnitStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UnitStatusEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BurnBridge_ServiceDesc.Streams[2], BurnBridge_WatchUnitStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchUnitStatusRequest, UnitStatusEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BurnBridge_WatchUnitStatusClient = grpc.ServerStreamingClient[UnitStatusEvent]

func (c *burnBridgeClient) GetDiscInfo(ctx context.Context, in *GetDiscInfoRequest, opts ...grpc.CallOption) (*GetDiscInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiscInfoResponse)
	err := c.cc.Invoke(ctx, BurnBridge_GetDiscInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) HandleMediaChange(ctx context.Context, in *HandleMediaChangeRequest, opts ...grpc.CallOption) (*HandleMediaChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleMediaChangeResponse)
	err := c.cc.Invoke(ctx, BurnBridge_HandleMediaChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) HandleTray(ctx context.Context, in *HandleTrayRequest, opts ...grpc.CallOption) (*HandleTrayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleTrayResponse)
	err := c.cc.Invoke(ctx, BurnBridge_HandleTray_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) GetImportedBucketState(ctx context.Context, in *GetImportedBucketStateRequest, opts ...grpc.CallOption) (*GetImportedBucketStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetImportedBucketStateResponse)
	err := c.cc.Invoke(ctx, BurnBridge_GetImportedBucketState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) DeleteObjects(ctx context.Context, in *DeleteObjectsRequest, opts ...grpc.CallOption) (*DeleteObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectsResponse)
	err := c.cc.Invoke(ctx, BurnBridge_DeleteObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) ListMetadataDbVersions(ctx context.Context, in *ListMetadataDbVersionsRequest, opts ...grpc.CallOption) (*ListMetadataDbVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMetadataDbVersionsResponse)
	err := c.cc.Invoke(ctx, BurnBridge_ListMetadataDbVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) RestoreMetadataDbVersion(ctx context.Context, in *RestoreMetadataDbVersionRequest, opts ...grpc.CallOption) (*RestoreMetadataDbVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreMetadataDbVersionResponse)
	err := c.cc.Invoke(ctx, BurnBridge_RestoreMetadataDbVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) GetAnchorStatus(ctx context.Context, in *GetAnchorStatusRequest, opts ...grpc.CallOption) (*GetAnchorStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnchorStatusResponse)
	err := c.cc.Invoke(ctx, BurnBridge_GetAnchorStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) ConfigureRuntimeOptions(ctx context.Context, in *ConfigureRuntimeOptionsRequest, opts ...grpc.CallOption) (*ConfigureRuntimeOptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureRuntimeOptionsResponse)
	err := c.cc.Invoke(ctx, BurnBridge_ConfigureRuntimeOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) FinalizeLayout(ctx context.Context, in *FinalizeLayoutRequest, opts ...grpc.CallOption) (*FinalizeLayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeLayoutResponse)
	err := c.cc.Invoke(ctx, BurnBridge_FinalizeLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) UpdateLicense(ctx context.Context, in *UpdateLicenseRequest, opts ...grpc.CallOption) (*UpdateLicenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLicenseResponse)
	err := c.cc.Invoke(ctx, BurnBridge_UpdateLicense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *burnBridgeClient) UploadUpgradePackage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadUpgradePackageChunk, UploadUpgradePackageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BurnBridge_ServiceDesc.Streams[3], BurnBridge_UploadUpgradePackage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadUpgradePackageChunk, UploadUpgradePackageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BurnBridge_UploadUpgradePackageClient = grpc.ClientStreamingClient[UploadUpgradePackageChunk, UploadUpgradePackageResponse]

func (c *burnBridgeClient) ApplyUpgrade(ctx context.Context, in *ApplyUpgradeRequest, opts ...grpc.CallOption) (*ApplyUpgradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyUpgradeResponse)
	err := c.cc.Invoke(ctx, BurnBridge_ApplyUpgrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BurnBridgeServer is the server API for BurnBridge service.
// All implementations must embed UnimplementedBurnBridgeServer
// for forward compatibility.
//
// BurnBridge recorder API.
//
// Compatibility goal:
// - Keep wire fields compatible with versitygw/backend/burnbridge/proto/burnbridge.proto
// - Allow direct interop between Go gateway and .NET Core BurnServer
type BurnBridgeServer interface {
	// Query recorder service version and runtime metadata.
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	// Create a logical write job for one S3 object.
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	// Bidirectional upload stream.
	// Server should ack per logical segment and optionally emit final summary ack.
	UploadObject(grpc.BidiStreamingServer[UploadObjectChunk, UploadObjectAck]) error
	// Finalize a job and persist layout/session metadata.
	CommitJob(context.Context, *CommitJobRequest) (*CommitJobResponse, error)
	// Finalize multiple uploaded jobs in one recorder drain/flush cycle.
	CommitJobBatch(context.Context, *CommitJobBatchRequest) (*CommitJobBatchResponse, error)
	// Query current job status.
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	// Request cooperative cancel.
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	// Read object bytes by (bucket, object_key) from offset.
	// length == 0 means stream to object end.
	ReadObject(*ReadObjectRequest, grpc.ServerStreamingServer[ReadObjectChunk]) error
	// Register pull source so recorder can fetch bytes directly from S3-compatible endpoint.
	RegisterS3ObjectPullSource(context.Context, *RegisterS3ObjectPullSourceRequest) (*RegisterS3ObjectPullSourceResponse, error)
	// Probe whether current unit/session is ready for I/O.
	TestUnitReady(context.Context, *TestUnitReadyRequest) (*TestUnitReadyResponse, error)
	// Subscribe to recorder unit/media readiness updates.
	WatchUnitStatus(*WatchUnitStatusRequest, grpc.ServerStreamingServer[UnitStatusEvent]) error
	// Query drive + disc information.
	GetDiscInfo(context.Context, *GetDiscInfoRequest) (*GetDiscInfoResponse, error)
	// Explicitly notify the recorder about a media insert/remove event.
	HandleMediaChange(context.Context, *HandleMediaChangeRequest) (*HandleMediaChangeResponse, error)
	// Explicitly open or close the recorder tray.
	HandleTray(context.Context, *HandleTrayRequest) (*HandleTrayResponse, error)
	// Return the currently imported on-disc metadata snapshot maintained by the recorder.
	GetImportedBucketState(context.Context, *GetImportedBucketStateRequest) (*GetImportedBucketStateResponse, error)
	// Mark one or more objects as logically deleted in recorder metadata.
	DeleteObjects(context.Context, *DeleteObjectsRequest) (*DeleteObjectsResponse, error)
	// List metadata database artifact versions known by the recorder.
	ListMetadataDbVersions(context.Context, *ListMetadataDbVersionsRequest) (*ListMetadataDbVersionsResponse, error)
	// Restore a metadata database artifact generation as the recorder's current working view.
	RestoreMetadataDbVersion(context.Context, *RestoreMetadataDbVersionRequest) (*RestoreMetadataDbVersionResponse, error)
	// Report BRS anchor state for the active disc/bucket.
	GetAnchorStatus(context.Context, *GetAnchorStatusRequest) (*GetAnchorStatusResponse, error)
	// Configure recorder runtime-only options without editing config files or restarting.
	ConfigureRuntimeOptions(context.Context, *ConfigureRuntimeOptionsRequest) (*ConfigureRuntimeOptionsResponse, error)
	// Finalize accumulated UDF layout on disc using persisted layout metadata (closes stream write session).
	FinalizeLayout(context.Context, *FinalizeLayoutRequest) (*FinalizeLayoutResponse, error)
	// Replace recorder license.xml content and optionally reload the shared burner host.
	UpdateLicense(context.Context, *UpdateLicenseRequest) (*UpdateLicenseResponse, error)
	// Upload an upgrade package into the recorder staging directory.
	UploadUpgradePackage(grpc.ClientStreamingServer[UploadUpgradePackageChunk, UploadUpgradePackageResponse]) error
	// Execute the configured recorder upgrade apply command for a staged package.
	ApplyUpgrade(context.Context, *ApplyUpgradeRequest) (*ApplyUpgradeResponse, error)
	mustEmbedUnimplementedBurnBridgeServer()
}

// UnimplementedBurnBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBurnBridgeServer struct{}

func (UnimplementedBurnBridgeServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedBurnBridgeServer) CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedBurnBridgeServer) UploadObject(grpc.BidiStreamingServer[UploadObjectChunk, UploadObjectAck]) error {
	return status.Error(codes.Unimplemented, "method UploadObject not implemented")
}
func (UnimplementedBurnBridgeServer) CommitJob(context.Context, *CommitJobRequest) (*CommitJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitJob not implemented")
}
func (UnimplementedBurnBridgeServer) CommitJobBatch(context.Context, *CommitJobBatchRequest) (*CommitJobBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitJobBatch not implemented")
}
func (UnimplementedBurnBridgeServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedBurnBridgeServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedBurnBridgeServer) ReadObject(*ReadObjectRequest, grpc.ServerStreamingServer[ReadObjectChunk]) error {
	return status.Error(codes.Unimplemented, "method ReadObject not implemented")
}
func (UnimplementedBurnBridgeServer) RegisterS3ObjectPullSource(context.Context, *RegisterS3ObjectPullSourceRequest) (*RegisterS3ObjectPullSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterS3ObjectPullSource not implemented")
}
func (UnimplementedBurnBridgeServer) TestUnitReady(context.Context, *TestUnitReadyRequest) (*TestUnitReadyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestUnitReady not implemented")
}
func (UnimplementedBurnBridgeServer) WatchUnitStatus(*WatchUnitStatusRequest, grpc.ServerStreamingServer[UnitStatusEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchUnitStatus not implemented")
}
func (UnimplementedBurnBridgeServer) GetDiscInfo(context.Context, *GetDiscInfoRequest) (*GetDiscInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiscInfo not implemented")
}
func (UnimplementedBurnBridgeServer) HandleMediaChange(context.Context, *HandleMediaChangeRequest) (*HandleMediaChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleMediaChange not implemented")
}
func (UnimplementedBurnBridgeServer) HandleTray(context.Context, *HandleTrayRequest) (*HandleTrayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleTray not implemented")
}
func (UnimplementedBurnBridgeServer) GetImportedBucketState(context.Context, *GetImportedBucketStateRequest) (*GetImportedBucketStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImportedBucketState not implemented")
}
func (UnimplementedBurnBridgeServer) DeleteObjects(context.Context, *DeleteObjectsRequest) (*DeleteObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteObjects not implemented")
}
func (UnimplementedBurnBridgeServer) ListMetadataDbVersions(context.Context, *ListMetadataDbVersionsRequest) (*ListMetadataDbVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMetadataDbVersions not implemented")
}
func (UnimplementedBurnBridgeServer) RestoreMetadataDbVersion(context.Context, *RestoreMetadataDbVersionRequest) (*RestoreMetadataDbVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreMetadataDbVersion not implemented")
}
func (UnimplementedBurnBridgeServer) GetAnchorStatus(context.Context, *GetAnchorStatusRequest) (*GetAnchorStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnchorStatus not implemented")
}
func (UnimplementedBurnBridgeServer) ConfigureRuntimeOptions(context.Context, *ConfigureRuntimeOptionsRequest) (*ConfigureRuntimeOptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureRuntimeOptions not implemented")
}
func (UnimplementedBurnBridgeServer) FinalizeLayout(context.Context, *FinalizeLayoutRequest) (*FinalizeLayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeLayout not implemented")
}
func (UnimplementedBurnBridgeServer) UpdateLicense(context.Context, *UpdateLicenseRequest) (*UpdateLicenseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLicense not implemented")
}
func (UnimplementedBurnBridgeServer) UploadUpgradePackage(grpc.ClientStreamingServer[UploadUpgradePackageChunk, UploadUpgradePackageResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadUpgradePackage not implemented")
}
func (UnimplementedBurnBridgeServer) ApplyUpgrade(context.Context, *ApplyUpgradeRequest) (*ApplyUpgradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyUpgrade not implemented")
}
func (UnimplementedBurnBridgeServer) mustEmbedUnimplementedBurnBridgeServer() {}
func (UnimplementedBurnBridgeServer) testEmbeddedByValue()                    {}

// UnsafeBurnBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BurnBridgeServer will
// result in compilation errors.
type UnsafeBurnBridgeServer interface {
	mustEmbedUnimplementedBurnBridgeServer()
}

func RegisterBurnBridgeServer(s grpc.ServiceRegistrar, srv BurnBridgeServer) {
	// If the following call panics, it indicates UnimplementedBurnBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BurnBridge_ServiceDesc, srv)
}

func _BurnBridge_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_CreateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_UploadObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BurnBridgeServer).UploadObject(&grpc.GenericServerStream[UploadObjectChunk, UploadObjectAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BurnBridge_UploadObjectServer = grpc.BidiStreamingServer[UploadObjectChunk, UploadObjectAck]

func _BurnBridge_CommitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).CommitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_CommitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).CommitJob(ctx, req.(*CommitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_CommitJobBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitJobBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).CommitJobBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_CommitJobBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).CommitJobBatch(ctx, req.(*CommitJobBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_ReadObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadObjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BurnBridgeServer).ReadObject(m, &grpc.GenericServerStream[ReadObjectRequest, ReadObjectChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BurnBridge_ReadObjectServer = grpc.ServerStreamingServer[ReadObjectChunk]

func _BurnBridge_RegisterS3ObjectPullSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterS3ObjectPullSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).RegisterS3ObjectPullSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_RegisterS3ObjectPullSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).RegisterS3ObjectPullSource(ctx, req.(*RegisterS3ObjectPullSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_TestUnitReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestUnitReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).TestUnitReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_TestUnitReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).TestUnitReady(ctx, req.(*TestUnitReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_WatchUnitStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchUnitStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BurnBridgeServer).WatchUnitStatus(m, &grpc.GenericServerStream[WatchUnitStatusRequest, UnitStatusEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BurnBridge_WatchUnitStatusServer = grpc.ServerStreamingServer[UnitStatusEvent]

func _BurnBridge_GetDiscInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).GetDiscInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_GetDiscInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).GetDiscInfo(ctx, req.(*GetDiscInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_HandleMediaChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleMediaChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).HandleMediaChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_HandleMediaChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).HandleMediaChange(ctx, req.(*HandleMediaChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_HandleTray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleTrayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).HandleTray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_HandleTray_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).HandleTray(ctx, req.(*HandleTrayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_GetImportedBucketState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImportedBucketStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).GetImportedBucketState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_GetImportedBucketState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).GetImportedBucketState(ctx, req.(*GetImportedBucketStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_DeleteObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).DeleteObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_DeleteObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).DeleteObjects(ctx, req.(*DeleteObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_ListMetadataDbVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMetadataDbVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).ListMetadataDbVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_ListMetadataDbVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).ListMetadataDbVersions(ctx, req.(*ListMetadataDbVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_RestoreMetadataDbVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreMetadataDbVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).RestoreMetadataDbVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_RestoreMetadataDbVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).RestoreMetadataDbVersion(ctx, req.(*RestoreMetadataDbVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_GetAnchorStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnchorStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).GetAnchorStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_GetAnchorStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).GetAnchorStatus(ctx, req.(*GetAnchorStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_ConfigureRuntimeOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRuntimeOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).ConfigureRuntimeOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_ConfigureRuntimeOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).ConfigureRuntimeOptions(ctx, req.(*ConfigureRuntimeOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_FinalizeLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).FinalizeLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_FinalizeLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).FinalizeLayout(ctx, req.(*FinalizeLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_UpdateLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).UpdateLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_UpdateLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).UpdateLicense(ctx, req.(*UpdateLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BurnBridge_UploadUpgradePackage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BurnBridgeServer).UploadUpgradePackage(&grpc.GenericServerStream[UploadUpgradePackageChunk, UploadUpgradePackageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BurnBridge_UploadUpgradePackageServer = grpc.ClientStreamingServer[UploadUpgradePackageChunk, UploadUpgradePackageResponse]

func _BurnBridge_ApplyUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyUpgradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnBridgeServer).ApplyUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BurnBridge_ApplyUpgrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnBridgeServer).ApplyUpgrade(ctx, req.(*ApplyUpgradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BurnBridge_ServiceDesc is the grpc.ServiceDesc for BurnBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BurnBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "burnbridge.v1.BurnBridge",
	HandlerType: (*BurnBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _BurnBridge_GetVersion_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _BurnBridge_CreateJob_Handler,
		},
		{
			MethodName: "CommitJob",
			Handler:    _BurnBridge_CommitJob_Handler,
		},
		{
			MethodName: "CommitJobBatch",
			Handler:    _BurnBridge_CommitJobBatch_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _BurnBridge_GetJobStatus_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _BurnBridge_CancelJob_Handler,
		},
		{
			MethodName: "RegisterS3ObjectPullSource",
			Handler:    _BurnBridge_RegisterS3ObjectPullSource_Handler,
		},
		{
			MethodName: "TestUnitReady",
			Handler:    _BurnBridge_TestUnitReady_Handler,
		},
		{
			MethodName: "GetDiscInfo",
			Handler:    _BurnBridge_GetDiscInfo_Handler,
		},
		{
			MethodName: "HandleMediaChange",
			Handler:    _BurnBridge_HandleMediaChange_Handler,
		},
		{
			MethodName: "HandleTray",
			Handler:    _BurnBridge_HandleTray_Handler,
		},
		{
			MethodName: "GetImportedBucketState",
			Handler:    _BurnBridge_GetImportedBucketState_Handler,
		},
		{
			MethodName: "DeleteObjects",
			Handler:    _BurnBridge_DeleteObjects_Handler,
		},
		{
			MethodName: "ListMetadataDbVersions",
			Handler:    _BurnBridge_ListMetadataDbVersions_Handler,
		},
		{
			MethodName: "RestoreMetadataDbVersion",
			Handler:    _BurnBridge_RestoreMetadataDbVersion_Handler,
		},
		{
			MethodName: "GetAnchorStatus",
			Handler:    _BurnBridge_GetAnchorStatus_Handler,
		},
		{
			MethodName: "ConfigureRuntimeOptions",
			Handler:    _BurnBridge_ConfigureRuntimeOptions_Handler,
		},
		{
			MethodName: "FinalizeLayout",
			Handler:    _BurnBridge_FinalizeLayout_Handler,
		},
		{
			MethodName: "UpdateLicense",
			Handler:    _BurnBridge_UpdateLicense_Handler,
		},
		{
			MethodName: "ApplyUpgrade",
			Handler:    _BurnBridge_ApplyUpgrade_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadObject",
			Handler:       _BurnBridge_UploadObject_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReadObject",
			Handler:       _BurnBridge_ReadObject_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchUnitStatus",
			Handler:       _BurnBridge_WatchUnitStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadUpgradePackage",
			Handler:       _BurnBridge_UploadUpgradePackage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "burnbridge.proto",
}
